"""
Force create users table if it's missing.
This will run the SQL directly to create the table.
"""
import os
import sys
import django

# Setup Django
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
django.setup()

from django.db import connection

def create_users_table():
    """Create users table directly if it doesn't exist."""
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'users'
            );
        """)
        exists = cursor.fetchone()[0]
        
        if exists:
            print("[INFO] Users table already exists!")
            return True
        
        print("[INFO] Users table not found. Creating it...")
        
        try:
            # Create the users table
            cursor.execute("""
                CREATE TABLE "users" (
                    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "password" varchar(128) NOT NULL,
                    "last_login" timestamp with time zone NULL,
                    "is_superuser" boolean NOT NULL,
                    "email" varchar(255) NOT NULL UNIQUE,
                    "first_name" varchar(150) NOT NULL,
                    "last_name" varchar(150) NOT NULL,
                    "is_active" boolean NOT NULL,
                    "is_staff" boolean NOT NULL,
                    "date_joined" timestamp with time zone NOT NULL
                );
            """)
            
            # Create indexes
            cursor.execute("""
                CREATE INDEX "users_email_0ea73cca_like" ON "users" ("email" varchar_pattern_ops);
            """)
            
            # Create junction tables for many-to-many relationships
            cursor.execute("""
                CREATE TABLE "users_groups" (
                    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "user_id" bigint NOT NULL,
                    "group_id" integer NOT NULL
                );
            """)
            
            cursor.execute("""
                CREATE TABLE "users_user_permissions" (
                    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "user_id" bigint NOT NULL,
                    "permission_id" integer NOT NULL
                );
            """)
            
            # Add constraints
            cursor.execute("""
                ALTER TABLE "users_groups" 
                ADD CONSTRAINT "users_groups_user_id_group_id_fc7788e8_uniq" 
                UNIQUE ("user_id", "group_id");
            """)
            
            cursor.execute("""
                ALTER TABLE "users_groups" 
                ADD CONSTRAINT "users_groups_user_id_f500bee5_fk_users_id" 
                FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
            """)
            
            cursor.execute("""
                ALTER TABLE "users_groups" 
                ADD CONSTRAINT "users_groups_group_id_2f3517aa_fk_auth_group_id" 
                FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
            """)
            
            cursor.execute("""
                CREATE INDEX "users_groups_user_id_f500bee5" ON "users_groups" ("user_id");
            """)
            
            cursor.execute("""
                CREATE INDEX "users_groups_group_id_2f3517aa" ON "users_groups" ("group_id");
            """)
            
            cursor.execute("""
                ALTER TABLE "users_user_permissions" 
                ADD CONSTRAINT "users_user_permissions_user_id_permission_id_3b86cbdf_uniq" 
                UNIQUE ("user_id", "permission_id");
            """)
            
            cursor.execute("""
                ALTER TABLE "users_user_permissions" 
                ADD CONSTRAINT "users_user_permissions_user_id_92473840_fk_users_id" 
                FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
            """)
            
            cursor.execute("""
                ALTER TABLE "users_user_permissions" 
                ADD CONSTRAINT "users_user_permissio_permission_id_6d08dcd2_fk_auth_perm" 
                FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
            """)
            
            cursor.execute("""
                CREATE INDEX "users_user_permissions_user_id_92473840" ON "users_user_permissions" ("user_id");
            """)
            
            cursor.execute("""
                CREATE INDEX "users_user_permissions_permission_id_6d08dcd2" ON "users_user_permissions" ("permission_id");
            """)
            
            print("[SUCCESS] Users table created!")
            
            # Now run migrations to add additional fields
            print("\n[INFO] Running migrations to add additional fields...")
            from django.core.management import execute_from_command_line
            execute_from_command_line(['manage.py', 'migrate', 'users'])
            
            return True
            
        except Exception as e:
            print(f"[ERROR] Failed to create table: {e}")
            print("\nTry running migrations instead:")
            print("  python manage.py migrate users zero")
            print("  python manage.py migrate users")
            return False

if __name__ == '__main__':
    create_users_table()

