# Generated by Django 5.2.9 on 2026-01-19 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('functional', 'Functional'), ('regression', 'Regression'), ('performance', 'Performance'), ('accessibility', 'Accessibility')], help_text='Type of test', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', help_text='Test status', max_length=20)),
                ('pass_rate', models.IntegerField(default=0, help_text='Percentage of tests that passed')),
                ('fail_rate', models.IntegerField(default=0, help_text='Percentage of tests that failed')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(help_text='Application being tested', on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='applications.application')),
            ],
            options={
                'verbose_name': 'Test Run',
                'verbose_name_plural': 'Test Runs',
                'db_table': 'test_runs',
                'ordering': ['-started_at'],
            },
        ),
    ]
