# Generated by Django 5.0.1 on 2026-01-19 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_testrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Screenshot image file', upload_to='screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_run', models.ForeignKey(help_text='Test run this screenshot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='applications.testrun')),
            ],
            options={
                'verbose_name': 'Screenshot',
                'verbose_name_plural': 'Screenshots',
                'db_table': 'screenshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
