# Generated by Django 5.0.1 on 2026-01-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='cloudinary_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL of the screenshot', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(blank=True, help_text='Screenshot image file', null=True, upload_to='screenshots/'),
        ),
    ]
