# Generated by Django 5.0.1 on 2026-01-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_screenshot_cloudinary_url_alter_screenshot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='login_url',
            field=models.URLField(blank=True, help_text='Login URL for auth testing', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='signup_url',
            field=models.URLField(blank=True, help_text='Signup URL for auth testing', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='test_password',
            field=models.CharField(blank=True, help_text='Password for automated testing', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='test_username',
            field=models.CharField(blank=True, help_text='Username for automated testing', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='check_auth',
            field=models.BooleanField(default=False, help_text='Whether to test login/signup functionality'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='check_broken_links',
            field=models.BooleanField(default=False, help_text='Whether to check for broken links'),
        ),
    ]
