# Generated by Django 5.0.1 on 2026-01-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_login_url_application_signup_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='test_type',
            field=models.CharField(choices=[('functional', 'Functional'), ('regression', 'Regression'), ('performance', 'Performance'), ('accessibility', 'Accessibility'), ('broken_links', 'Broken Links'), ('authentication', 'Authentication Flow')], help_text='Type of test', max_length=20),
        ),
    ]
