# Generated by Django 5.0.1 on 2026-01-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_testrun_test_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='signup_url',
        ),
        migrations.AlterField(
            model_name='testrun',
            name='check_auth',
            field=models.BooleanField(default=False, help_text='Whether to test login functionality'),
        ),
    ]
