# Generated by Django 5.2.9 on 2026-01-30 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_remove_application_signup_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('playwright_trace', 'Playwright Trace'), ('playwright_video', 'Playwright Video'), ('before_step', 'Before Step Screenshot'), ('after_step', 'After Step Screenshot')], help_text='Type of artifact', max_length=50)),
                ('url', models.URLField(help_text='Cloudinary URL or local path to the artifact', max_length=500)),
                ('step_name', models.CharField(blank=True, help_text="Optional step name (e.g., 'login', 'submit_form')", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_run', models.ForeignKey(help_text='Test run this artifact belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='applications.testrun')),
            ],
            options={
                'verbose_name': 'Test Artifact',
                'verbose_name_plural': 'Test Artifacts',
                'db_table': 'test_artifacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
