# Generated by Django 5.2.9 on 2026-02-04 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_add_test_artifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the test case', max_length=255)),
                ('description', models.TextField(help_text='Description of what this test verifies')),
                ('test_type', models.CharField(choices=[('functional', 'Functional'), ('regression', 'Regression'), ('performance', 'Performance'), ('accessibility', 'Accessibility'), ('broken_links', 'Broken Links'), ('authentication', 'Authentication Flow')], help_text='Type of test', max_length=20)),
                ('steps_json', models.JSONField(default=list, help_text='JSON array of test steps')),
                ('expected_results', models.TextField(help_text='Overall expected outcome')),
                ('tags', models.JSONField(default=list, help_text='Tags for categorization')),
                ('estimated_duration', models.CharField(default='5 minutes', help_text='Estimated test duration', max_length=50)),
                ('is_ai_generated', models.BooleanField(default=True, help_text='Whether this was AI-generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(help_text='Application this test case belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='generated_test_cases', to='applications.application')),
            ],
            options={
                'verbose_name': 'Generated Test Case',
                'verbose_name_plural': 'Generated Test Cases',
                'db_table': 'generated_test_cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
