# Generated by Django 5.0.1 on 2026-02-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_add_test_artifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='cancel_reason',
            field=models.CharField(blank=True, help_text='Reason for cancellation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='cancel_requested',
            field=models.BooleanField(default=False, help_text='Whether cancellation was requested'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, help_text='When cancellation was requested', null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='canceled_at',
            field=models.DateTimeField(blank=True, help_text='When test was canceled', null=True),
        ),
    ]
