# Generated by Django 5.x on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0010_add_cancel_fields"),
        ("applications", "0010_generatedtestcase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testrun",
            name="test_type",
            field=models.CharField(
                choices=[
                    ("general", "General (Full Suite)"),
                    ("functional", "Functional"),
                    ("regression", "Regression"),
                    ("performance", "Performance"),
                    ("accessibility", "Accessibility"),
                    ("broken_links", "Broken Links"),
                    ("authentication", "Authentication Flow"),
                ],
                help_text="Type of test",
                max_length=20,
            ),
        ),
    ]

