# Generated by Django 5.0.1 on 2026-02-19 08:39

import apps.applications.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_testrunstepresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='login_url',
            field=apps.applications.fields.EncryptedURLField(blank=True, help_text='Login URL for auth testing', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='test_password',
            field=apps.applications.fields.EncryptedCharField(blank=True, help_text='Password for automated testing', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='test_username',
            field=apps.applications.fields.EncryptedCharField(blank=True, help_text='Username for automated testing', max_length=255, null=True),
        ),
    ]
