# Generated by Django 5.2.9 on 2026-02-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_alter_application_login_url_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['application', 'status'], name='test_runs_applica_b1a352_idx'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['application', '-started_at'], name='test_runs_applica_79972b_idx'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['status', '-started_at'], name='test_runs_status_d35b46_idx'),
        ),
    ]
