# Generated by Django 5.0.1 on 2026-01-21 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0004_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='Brief summary of the test results')),
                ('detailed_report', models.TextField(help_text='Detailed report of the test execution')),
                ('issues_json', models.JSONField(blank=True, default=list, help_text='JSON array of issues found during testing')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the report was created')),
                ('test_run', models.OneToOneField(help_text='The test run associated with this report', on_delete=django.db.models.deletion.CASCADE, related_name='report', to='applications.testrun')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
