# Generated by Django 5.2.9 on 2026-01-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='console_logs_json',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of full console log history'),
        ),
    ]
