# Generated by Django 5.2.9 on 2026-01-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the application', max_length=255, unique=True)),
                ('url', models.URLField(help_text='URL of the application')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the application was added')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['name'],
            },
        ),
    ]
