# Generated by Django 5.2.9 on 2026-01-19 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_runs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='Brief summary of the test results')),
                ('detailed_report', models.TextField(help_text='Detailed report of the test execution')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the report was created')),
                ('test_run', models.OneToOneField(help_text='The test run associated with this report', on_delete=django.db.models.deletion.CASCADE, related_name='report', to='test_runs.testrun')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
