# Generated by Django 5.2.9 on 2026-01-19 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('FULL', 'Full'), ('UI_UX', 'UI/UX'), ('FUNCTIONAL', 'Functional'), ('CUSTOM', 'Custom')], default='FULL', help_text='Type of test to run', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Current status of the test run', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the test run started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the test run completed', null=True)),
                ('application', models.ForeignKey(help_text='The application being tested', on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='applications.application')),
            ],
            options={
                'verbose_name': 'Test Run',
                'verbose_name_plural': 'Test Runs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['application', '-started_at'], name='test_runs_t_applica_5e7ba8_idx'), models.Index(fields=['status'], name='test_runs_t_status_d47336_idx')],
            },
        ),
    ]
