# Generated by Django 5.2.9 on 2026-01-19 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_runs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='URL to the screenshot image')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the screenshot was captured')),
                ('test_run', models.ForeignKey(help_text='The test run this screenshot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='test_runs.testrun')),
            ],
            options={
                'verbose_name': 'Screenshot',
                'verbose_name_plural': 'Screenshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['test_run', '-created_at'], name='screenshots_test_ru_76f087_idx')],
            },
        ),
    ]
